import Head from "next/head";
import { FC, ReactNode } from "react";
import { Sidebar } from "../SideBar";
import { Open_Sans } from "next/font/google";
import styles from "./wrapper.module.css";

interface WrapperProps {
  children?: ReactNode;
}
const sans = Open_Sans({ subsets: ["latin"] });

export const Wrapper: FC<WrapperProps> = ({ children }) => {
  return (
    <>
      <style jsx global>{`
        html {
          font-family: ${sans.style.fontFamily};
        }
      `}</style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.wrapper}>
        <Sidebar />
        <div className={styles.content}>{children}</div>
      </main>
    </>
  );
};
